apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arun-lab-test

resources:
  - ../../base
  - google-key-sealed.yaml


# Add a label to indicate the production environment.
commonLabels:
  environment: production

# Override APP_PORT if production uses a different port (e.g., 80).
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_PORT=80

# Override the default ingress host with a production domain.
patchesStrategicMerge:
  - ingress-patch.yaml
  - patch-service-nodeport.yaml
