apiVersion: apps/v1
kind: Deployment
metadata:
  name: track24-api
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: api
        image: ${ECR_REPOSITORY_URI}:latest
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi