apiVersion: apps/v1
kind: Deployment
metadata:
  name: track24-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        image: my-api:prod
        env:
        - name: NODE_ENV
          value: "development"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi